name: Update Wales Results Calendar

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests ics pytz

      - name: Run script
        run: python convert.py

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.ics
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Wales results calendar"
            git push
          fi
